###################
## Config        ##
###################

[config]
skip_core_tasks = true

###################
## Test          ##
###################

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-watch]
command = "cargo"
args = ["watch", "-w", "../../shared/rust", "-w", ".", "-x", "test --features local-quiet -- --nocapture"]

###################
## Dev           ##
###################

[tasks.dev-noquiet]
command = "systemfd"
args = ["--no-pid", "-s", "http::8080", "--", "cargo", "watch", "-w", "../../config/rust/src", "-w", "../../shared/rust/src", "-w", "../_core/rust/src", "-w", "-w", ".", "-x", "run --features"]
