[package]
name = "ji-cloud-api"
version = "0.1.0"
authors = ["dakom <david.komer@gmail.com>"]
edition = "2018"

[dependencies]
actix-cors = "0.3.0-alpha.1"
actix-rt = "1.0.0"
actix-service = "1.0.5"
actix-web = "3.0.0-beta.1"
anyhow = "1.0.32"
cfg-if = "^0.1"
chrono = "0.4.13"
config = {path = "../../config/rust"}
core = {path = "../_core/rust"}
dotenv = "^0.15"
futures = "0.3.5"
futures-util = "0.3.4"
jsonwebtoken = "7.2"
lazy_static = "^1.4"
listenfd = {version = "^0.3", optional = true }
log = "^0.4"
once_cell = "1.4.0"
openssl = { version = "^0.10", features = ["vendored"], optional = true }
percent-encoding = "2.1.0"
rand = "0.7"
reqwest = { version = "^0.10", features = ["json"] }
serde = { version = "^1.0", features = ["derive"] }
serde_derive = "^1.0"
serde_json = "^1.0"
shared = {path = "../../shared/rust", features = ["backend"]}
simplelog = "^0.8"
strum = "^0.18"
strum_macros = "^0.18"
time = "0.2.16"
tokio = { version = "^0.2", features = ["full"] }
uuid = "0.8.1"

[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = [ "runtime-tokio", "macros", "postgres", "uuid", "json", "chrono", "offline"]

[features]
local = ["listenfd", "core/local"]
release = ["core/release", "openssl"]
sandbox = ["core/sandbox", "openssl"]
quiet = []
sqlproxy = []
local-quiet = ["local", "quiet"]
