###################
## Config        ##
###################

[config]
skip_core_tasks = true

[env]
DOCKER_BUILDKIT = "1"

###################
## Gcloud        ##
###################

[tasks.gcloud-configure-docker]
script_runner = "@shell"
script = ["gcloud auth configure-docker"]

###################
## PAGES         ##
###################

#------Release-----------#
[tasks.release-pages]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-release-pages",
    "docker-publish-release-pages",
    "deploy-release-pages",
]}]

[tasks.docker-build-release-pages]
command = "docker"
args = ["build", "-f", "backend/pages/Dockerfile", "--target", "release", "-t", "gcr.io/ji-cloud/ji-cloud-pages:latest", "."]

[tasks.docker-publish-release-pages]
command = "docker"
args = ["push", "gcr.io/ji-cloud/ji-cloud-pages:latest"]

[tasks.deploy-release-pages]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-pages --project ji-cloud --region europe-west1 --image gcr.io/ji-cloud/ji-cloud-pages:latest --platform managed"]

#------Sandbox-----------#
[tasks.sandbox-pages]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-sandbox-pages",
    "docker-publish-sandbox-pages",
    "deploy-sandbox-pages",
]}]

[tasks.docker-build-sandbox-pages]
command = "docker"
args = ["build", "-f", "backend/pages/Dockerfile", "--target", "sandbox", "-t", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-pages-sandbox:latest", "."]

[tasks.docker-publish-sandbox-pages]
command = "docker"
args = ["push", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-pages-sandbox:latest"]

[tasks.deploy-sandbox-pages]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-pages-sandbox --project ji-cloud-developer-sandbox --region europe-west1 --image gcr.io/ji-cloud-developer-sandbox/ji-cloud-pages-sandbox:latest --platform managed"]

###################
## API           ##
###################

#------Release-----------#
[tasks.release-api]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-release-api",
    "docker-publish-release-api",
    "deploy-release-api",
]}]

[tasks.docker-build-release-api]
command = "docker"
args = ["build", "-f", "backend/api/Dockerfile", "--target", "release", "-t", "gcr.io/ji-cloud/ji-cloud-api:latest", "."]

[tasks.docker-publish-release-api]
command = "docker"
args = ["push", "gcr.io/ji-cloud/ji-cloud-api:latest"]

[tasks.deploy-release-api]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-api --project ji-cloud --region europe-west1 --image gcr.io/ji-cloud/ji-cloud-api:latest --platform managed"]

#------Sandbox-----------#
[tasks.sandbox-api]
run_task = [{name = [
    "gcloud-configure-docker",
    "docker-build-sandbox-api",
    "docker-publish-sandbox-api",
    "deploy-sandbox-api",
]}]

[tasks.docker-build-sandbox-api]
command = "docker"
args = ["build", "-f", "backend/api/Dockerfile", "--target", "sandbox", "-t", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-sandbox:latest", "."]

[tasks.docker-publish-sandbox-api]
command = "docker"
args = ["push", "gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-sandbox:latest"]

[tasks.deploy-sandbox-api]
script_runner = "@shell"
script = ["gcloud run deploy ji-cloud-api-sandbox --project ji-cloud-developer-sandbox --region europe-west1 --image gcr.io/ji-cloud-developer-sandbox/ji-cloud-api-sandbox:latest --platform managed"]

###################
## Fastly Purge  ##
###################
[tasks.copy-config-fastly-purge]
script_runner = "@shell"
script = ["cp -R ./config/js/ ./backend/fastly-purge/config/"]

#------Release-----------#
[tasks.release-fastly-purge]
run_task = [{name = [
	"copy-config-fastly-purge",
    "deploy-release-fastly-purge-frontend",
    "deploy-release-fastly-purge-storybook",
    "deploy-release-fastly-purge-media",
]}]


[tasks.deploy-release-fastly-purge-frontend]
script_runner = "@shell"
script = ["gcloud functions deploy purgeFrontendRelease --project ji-cloud --trigger-resource ji-cloud-frontend-origin-eu-001 --region europe-west1 --source backend/fastly-purge --runtime nodejs10 --trigger-event google.storage.object.finalize"]

[tasks.deploy-release-fastly-purge-storybook]
script_runner = "@shell"
script = ["gcloud functions deploy purgeStorybookRelease --project ji-cloud --trigger-resource ji-cloud-storybook-origin-eu-001 --region europe-west1 --source backend/fastly-purge --runtime nodejs10 --trigger-event google.storage.object.finalize"]

# the media is on release project since it's used by release project (media.jicloud.org)
[tasks.deploy-release-fastly-purge-media]
script_runner = "@shell"
script = ["gcloud functions deploy purgeMedia --project ji-cloud --trigger-resource ji-cloud-media-origin-eu-001 --region europe-west1 --source backend/fastly-purge --runtime nodejs10 --trigger-event google.storage.object.finalize"]

#------Sandbox-----------#

[tasks.sandbox-fastly-purge]
run_task = [{name = [
	"copy-config-fastly-purge",
    "deploy-sandbox-fastly-purge-frontend",
    "deploy-sandbox-fastly-purge-storybook",
    "deploy-sandbox-fastly-purge-docs",
]}]

[tasks.deploy-sandbox-fastly-purge-frontend]
script_runner = "@shell"
script = ["gcloud functions deploy purgeFrontendSandbox --project ji-cloud-developer-sandbox --trigger-resource ji-cloud-sandbox-frontend-origin-eu-001 --region europe-west1 --source backend/fastly-purge --runtime nodejs10 --trigger-event google.storage.object.finalize"]

[tasks.deploy-sandbox-fastly-purge-storybook]
script_runner = "@shell"
script = ["gcloud functions deploy purgeStorybookSandbox --project ji-cloud-developer-sandbox --trigger-resource ji-cloud-sandbox-storybook-origin-eu-001 --region europe-west1 --source backend/fastly-purge --runtime nodejs10 --trigger-event google.storage.object.finalize"]

# the docs is on sandbox project since it's for dev only 
[tasks.deploy-sandbox-fastly-purge-docs]
script_runner = "@shell"
script = ["gcloud functions deploy purgeDocs --project ji-cloud-developer-sandbox --trigger-resource ji-cloud-sandbox-docs-origin-eu-001 --region europe-west1 --source backend/fastly-purge --runtime nodejs10 --trigger-event google.storage.object.finalize"]
