[package]
name = "shared"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"
description = "shared types for ji cloud project"
license = "MIT OR Apache-2.0"

[dependencies]
actix-web = { version = "3.0.0-beta.1", optional = true }
anyhow = { version = "1.0.32" }
cfg-if = "^0.1"
chrono = { version = "0.4.13", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = { version = "2.1.1", features = ["serde"] }
uuid = { version = "0.8.1", features = ["serde"] }

[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = ["runtime-tokio", "macros", "postgres", "uuid", "json", "chrono", "offline", "migrate"]
optional = true

[features]
backend = ["sqlx", "actix-web"]
